language: c

install:
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ./repo
  - chmod a+x ./repo

before_script:
  - repo init -u https://github.com/bitpresso/android-custom-manifests.git
  - repo init -m adb-fastboot-for-mac.xml
  - repo sync

script:
  - make adb fastboot
